version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ontodb-postgres-${USER}  
    restart: always
    environment:
      POSTGRES_DB: OntoDb
      POSTGRES_USER: ontodb
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../init:/docker-entrypoint-initdb.d
      - ../data:/data
    networks:
      - ontodb-network

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: ontodb-jupyter-${USER}
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/home/jovyan/work
      - ../data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - ontodb-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  ontodb-network:
    driver: bridge
