version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: OntoDb
      POSTGRES_USER: ontodb
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ontodb -d OntoDb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - onto_network

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../data:/app/data
    environment:
      - DB_HOST=postgres
      - DB_NAME=OntoDb
      - DB_USER=ontodb
      - DB_PASSWORD=admin
    networks:
      - onto_network

networks:
  onto_network:
    driver: bridge

volumes:
  postgres_data:
